### PR TITLE
Add message author username in raid commands

### PR DESCRIPTION
**Pull request by cosmiccdev**

### CODE REVIEW

**Comment by cosmiccdev** [comment]
Crap, forgot to change the raid.test.js file as well. Let me do that before review.

**Comment by Moesgaarda** [comment]
I think the formatting could use some work 👋 

image

**Comment by cosmiccdev** [comment]
Let me do a little bit of formatting fixing and push that back up!

**Comment by cosmiccdev** [comment]
I did a slight bit of formatting fixes, now it should show as:

> **RAAAAAAAAAAAAAAAID⚔** with @Tekrus https://cuckoo.team/koa

Any suggestions for better formatting?

**Pull request merged**
