### PR TITLE
Makes the space in good morning/night optional

### LINKED ISSUE #111: Recognize "goodnight" as well as "good night"
When someone says "good night", horace properly reacts with a moon. However, "goodnight" does not trigger the same thing.

See pull request #69 for the proper class to edit.

### PR DESCRIPTION
**Pull request by debashisbiswas**
resolves #111 

Updated the regex that matches good morning/night so that the space between the words is now optional.

Found that citadelActions.js and greetingAction.js did the exact same thing, but only one was being used. This seemed to be the result of a merge conflict that was resolved incorrectly. I decided to keep citadelActions.js and deleted greetingAction.js - it was not referenced anywhere else.

### CODE REVIEW

**Review by ghost — APPROVED** [review]
Everything looks fine by me. Let me know when you're ready to merge.

**Review by Dendrobyte — APPROVED** [review]
👏

**Comment by debashisbiswas** [comment]
Should be good! I believe you can squash my extra commits into one commit when you're merging.

**Comment by ghost** [comment]
done!

**Pull request merged**
