### PR TITLE
The long awaited AFK feature!

### LINKED ISSUE #15: AFK feature
A user should be able to set an AFK message eg:
"!afk Out on a walk, DM if important" 

If a user is tagged in a channel while marked as AFK, Horace should post their AFK message.

If the user posts a message while AFK, they should be prompted by the bot if they want to remove their AFK status (should be confirmed by reacting to the bots message either a confirm (check mark) or deny (cross) emoji.

It would be preferable that the bot automatically reacts to its "remove afk" confirmation message with the two emojis, so the user will only have to click one of them to confirm.

After a user reacts to a confirmation message, the message from the bot should be removed.

Example from the previous version:
image

image

### PR DESCRIPTION
**Pull request by Zaph-x**
This pull request implements a feature, where users can mark themselves as AFK with a message to send, when they are tagged.
This should close #15 

Below are some examples on usage.
image
image
image

A follow-up action is triggered, only when the AFK user reacts to the embed shown in the last picture.

### CODE REVIEW

**Comment by ghost** [comment]
When the user sends a message in chat while AFK (i.e. the 3rd picture), could we send that message in DMs instead of the channel they send the message in? Thinking that might clutter the channel a little bit if the feature is used enough.

**Comment by Zaph-x** [comment]
Sure thing! However the message is automatically removed after 15 seconds. Should I go ahead and send it in a DM anyways?

**Comment by ghost** [comment]
Yeah, go ahead and keep it in DMs. Alex agrees: https://bit.ly/2JmlMvb

**Comment by Zaph-x** [comment]
So in this case, would it be all the messages that we are sending to DMs? Or just the ones in img 2 and 3? In the most recent commit, this is the case

**Comment by ghost** [comment]
That works perfectly! Also, does the bot delete the initial !afk command message, or does it stay in the channel after DMing the sender that they're AFK?

**Comment by Dendrobyte** [comment]
Horace should delete all commands regardless of what command it is, so as long as it uses the same command handling as others it will.

**Comment by Zaph-x** [comment]
It does indeed delete the command afterwards!

**Comment by ghost** [comment]
Then I will go ahead and mark this as approved! LMK when you're ready to merge.

**Review by ghost — APPROVED** [review]

**Pull request merged**
