### PR TITLE
Help to embed

### PR DESCRIPTION
**Pull request by ghost**
- Change help command output to an embed rather than a normal message.
- Disabled testing on individual commands due to problems w/ testing for embeds.

image

### CODE REVIEW

**Comment by Tekrus** [comment]
I'd love it if you added the prefix to usage and alises :D

**Comment by ghost** [comment]
Oops, forgot about getting to this last night! Tonight I've got a lot of work to get through but I'll hopefully take it up after!

**Comment by Dendrobyte** [comment]
How are we looking on this? Anything I can help update / give a second pair of eyes to in the meanwhile?

**Comment by ghost** [comment]
@Moesgaarda figured out how to add the prefix to the main command response, but am not sure what to do about aliases since it's all one description. Mind taking a quick look at what I could possibly do about that?

**Comment by ghost** [comment]
Ha! @Dendrobyte Just saw your comment after I made mine! Whoops! See what I wrote to Tek for what I need help on. Aliases is the last thing I need, besides unit testing not existing for embeds but I think we came to the conclusion that can be left out for a little bit.

**Comment by ghost** [comment]
Testing this tonight and then re-requesting review, let's see if we can get this merged ASAP since it's been in progress for so long LOL

**Comment by ghost** [comment]
Done and tested! Re requesting review now.

**Review by Tekrus — APPROVED** [review]

**Pull request merged**
