### PR TITLE
Added greeting reactions

### LINKED ISSUE #36: Good morning or night greetings
**Is your feature request related to a problem? Please describe.**
People love it when the bot greets them when they say good morning or goodnight, we should include a feature where the bot does so!

**Describe the solution you'd like**
When a message contains morning related keywords (good and morning in the sentence) or 
night related keywords (good and night in the sentence) should be reacted to with either a sun or a moon emoji.

**Additional context**
This feature should only work in the citadel channel.

### PR DESCRIPTION
**Pull request by Zaph-x**
This will add greetings to the messages  "good morning koa" and "good night koa". It will add a sun or mood reaction depending on the message. This will resolve #36 

It will require the config to contain a `citadelid` key, with the ID of the citadel channel.

### CODE REVIEW

**Comment by Moesgaarda** [comment]
This slightly conflicts with #42 which changes the format of the config file to have a roles and channels property, so depending on which one is merged first - the other will have to adjust format

**Comment by Zaph-x** [comment]
Shouldn't be too difficult to update. I'll have a look at #42 and see if I can implement the fix here, before either are merged

**Comment by Moesgaarda** [comment]
The other one has been merged now, so if you want to go ahead and look at the new structure, that would be neat! 🚀 

The new structure involves moving the check to a new folder, so we don't bloat the event files more than necessary.

**Comment by Moesgaarda** [comment]
Hi @Zaph-x - any progress in fixing the PR? 👋

**Comment by Moesgaarda** [comment]
This has now reached a week of inactivity, I'm closing it up to let other people handle the PR.

If it is fixed, feel free to re-open it PR.

**Pull request closed without merging**
