### PR TITLE
Remove old features

### LINKED ISSUE #205: Socials command
One command linking to Twitter, Goodreads, + website.

### PR DESCRIPTION
**Pull request by debashisbiswas**
This PR removes some of the old features of the bot that have almost never been used since their introduction a few years ago. We can use this space to discuss other features to remove before merging the PR.

### CODE REVIEW

**Review by ThatNerdSquared — COMMENTED** [review]
I'm not sure if `!choose` (still being used) or `!afk` (could be used more and not easy to rebuild) should be deleted. Also wondering if we can delete`!firstweek`, I don't see it being used at all and I think the article it links to is outdated. Otherwise it looks good!

**Comment by debashisbiswas** [comment]
I don't mind keeping the `!choose` command if it's getting some usage!

`!afk` was fixed at the beginning of the year, but it hasn't been used once all year - that was my motivation for removing it. I'm not sure how it provides value for the community... it's a cool command, but it's not worth maintaining if no one's interested in it (especially because we're going to upgrade discord.js soon). 

Commands like `!firstweek`, `!newsletter`, and `!article` were added to connect with the website. However, I don't see anyone using those either. We can discuss these in the engineering server

**Comment by debashisbiswas** [comment]
Alright, this one should be ready for review 👍

**Review by ThatNerdSquared — APPROVED** [review]
Looks great! Thanks for cleaning up the codebase.

**Pull request merged**
