### PR TITLE
Allow user to turn off AFK by running command again

### PR DESCRIPTION
**Pull request by zmontgo**

### CODE REVIEW

**Comment by zmontgo** [comment]
I'm imagining just removing the DM message at some point in the future but I've kept it now (with an edit) to help people transition to the new way of turning off AFK.

**Comment by ghost** [comment]
I'd rather not have this run off an error, would it be possible to just check before sending if it exists in the table?

**Comment by zmontgo** [comment]
Done, I've made it select then tell the length of the result. I've tested this and it works fine but it's a rather large change so I would feel better if you could test it to make absolutely certain before going live.

**Comment by ghost** [comment]
Going to go ahead and merge but will test again before deploy!

**Pull request merged**
